import { Layout } from "@/components/layout/Layout";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Calendar, Clock, BookOpen, Sparkles, RotateCcw, Plus, X, AlertTriangle } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";

const PLANNER_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/study-planner`;

export default function StudyPlanner() {
  const [subjects, setSubjects] = useState<string[]>([""]);
  const [weakSubjects, setWeakSubjects] = useState<string[]>([]);
  const [examDate, setExamDate] = useState("");
  const [hoursPerDay, setHoursPerDay] = useState(6);
  const [branch, setBranch] = useState("");
  const [semester, setSemester] = useState("");
  const [content, setContent] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [showResults, setShowResults] = useState(false);

  const addSubject = () => {
    if (subjects.length < 10) setSubjects([...subjects, ""]);
  };

  const removeSubject = (index: number) => {
    if (subjects.length > 1) setSubjects(subjects.filter((_, i) => i !== index));
  };

  const updateSubject = (index: number, value: string) => {
    const updated = [...subjects];
    updated[index] = value;
    setSubjects(updated);
  };

  const toggleWeakSubject = (subject: string) => {
    setWeakSubjects((prev) =>
      prev.includes(subject) ? prev.filter((s) => s !== subject) : [...prev, subject]
    );
  };

  const generatePlan = async () => {
    const validSubjects = subjects.filter((s) => s.trim());
    if (validSubjects.length === 0) return;

    setIsLoading(true);
    setContent("");
    setShowResults(true);

    try {
      const resp = await fetch(PLANNER_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
        },
        body: JSON.stringify({
          subjects: validSubjects,
          examDate,
          hoursPerDay,
          branch: branch.trim(),
          semester: semester.trim(),
          weakSubjects: weakSubjects.filter((s) => validSubjects.includes(s)),
        }),
      });

      if (!resp.ok || !resp.body) throw new Error("Failed to generate");

      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let fullContent = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });

        let newlineIndex: number;
        while ((newlineIndex = buffer.indexOf("\n")) !== -1) {
          let line = buffer.slice(0, newlineIndex);
          buffer = buffer.slice(newlineIndex + 1);
          if (line.endsWith("\r")) line = line.slice(0, -1);
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (jsonStr === "[DONE]") break;
          try {
            const parsed = JSON.parse(jsonStr);
            const delta = parsed.choices?.[0]?.delta?.content;
            if (delta) {
              fullContent += delta;
              setContent(fullContent);
            }
          } catch {
            buffer = line + "\n" + buffer;
            break;
          }
        }
      }
    } catch {
      setContent("❌ Failed to generate study plan. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const reset = () => {
    setContent("");
    setShowResults(false);
  };

  const validSubjects = subjects.filter((s) => s.trim());

  return (
    <Layout>
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 hero-gradient">
          <div className="absolute inset-0 hero-glow" />
          <div className="absolute top-20 left-10 w-72 h-72 bg-emerald-500/20 rounded-full blur-[100px] animate-float" />
        </div>
        <div className="container mx-auto px-4 py-16 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/20 backdrop-blur-md mb-6 border border-emerald-500/30">
              <Calendar className="w-4 h-4 text-emerald-400" />
              <span className="text-sm font-medium text-white">AI-Powered Planning</span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white font-display mb-4">
              Smart <span className="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">Study Planner</span>
            </h1>
            <p className="text-white/70 text-lg max-w-xl mx-auto">
              Get a personalized day-by-day study schedule generated by GURU AI
            </p>
          </div>
        </div>
      </section>

      <section className="py-16 bg-background">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-6 md:p-8 rounded-3xl bg-card border border-border/50 shadow-premium mb-8"
            >
              {/* Subjects */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-foreground mb-3">Subjects *</label>
                <div className="space-y-2">
                  {subjects.map((subject, i) => (
                    <div key={i} className="flex gap-2">
                      <input
                        type="text"
                        value={subject}
                        onChange={(e) => updateSubject(i, e.target.value)}
                        maxLength={100}
                        placeholder={`Subject ${i + 1} (e.g. Data Structures)`}
                        className="flex-1 input-premium"
                      />
                      {subjects.length > 1 && (
                        <Button variant="ghost" size="icon" onClick={() => removeSubject(i)} className="h-10 w-10 text-muted-foreground hover:text-destructive">
                          <X className="w-4 h-4" />
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
                {subjects.length < 10 && (
                  <Button variant="outline" size="sm" onClick={addSubject} className="mt-2 rounded-lg text-xs">
                    <Plus className="w-3 h-3 mr-1" /> Add Subject
                  </Button>
                )}
              </div>

              {/* Weak subjects */}
              {validSubjects.length > 0 && (
                <div className="mb-6">
                  <label className="block text-sm font-medium text-foreground mb-2 flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 text-amber-500" /> Weak Subjects (optional)
                  </label>
                  <div className="flex flex-wrap gap-2">
                    {validSubjects.map((subject) => (
                      <button
                        key={subject}
                        onClick={() => toggleWeakSubject(subject)}
                        className={`px-3 py-1.5 rounded-full text-xs font-medium transition-all ${
                          weakSubjects.includes(subject)
                            ? "bg-amber-500/20 text-amber-600 dark:text-amber-400 border border-amber-500/30"
                            : "bg-secondary text-muted-foreground border border-border hover:border-amber-500/30"
                        }`}
                      >
                        {subject}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2 flex items-center gap-2">
                    <Calendar className="w-4 h-4" /> Exam Date
                  </label>
                  <input type="date" value={examDate} onChange={(e) => setExamDate(e.target.value)} className="w-full input-premium" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2 flex items-center gap-2">
                    <Clock className="w-4 h-4" /> Hours/Day: {hoursPerDay}
                  </label>
                  <input type="range" min={2} max={12} value={hoursPerDay} onChange={(e) => setHoursPerDay(Number(e.target.value))} className="w-full accent-primary" />
                  <div className="flex justify-between text-xs text-muted-foreground mt-1">
                    <span>2h</span><span>12h</span>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-6">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Branch</label>
                  <input type="text" value={branch} onChange={(e) => setBranch(e.target.value)} maxLength={50} placeholder="e.g. CSE, ECE" className="w-full input-premium" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Semester</label>
                  <input type="text" value={semester} onChange={(e) => setSemester(e.target.value)} maxLength={20} placeholder="e.g. 5th" className="w-full input-premium" />
                </div>
              </div>

              <div className="flex gap-3">
                <Button
                  onClick={generatePlan}
                  disabled={isLoading || validSubjects.length === 0}
                  className="flex-1 btn-gradient rounded-xl py-6 text-base font-semibold shadow-glow hover:shadow-glow-lg transition-all duration-500"
                >
                  {isLoading ? (
                    <span className="flex items-center gap-2">
                      <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                      Generating Plan...
                    </span>
                  ) : (
                    <span className="flex items-center gap-2">
                      <Sparkles className="w-4 h-4" /> Generate Study Plan
                    </span>
                  )}
                </Button>
                {showResults && (
                  <Button onClick={reset} variant="outline" className="rounded-xl py-6 px-5">
                    <RotateCcw className="w-4 h-4" />
                  </Button>
                )}
              </div>
            </motion.div>

            {/* Results */}
            <AnimatePresence>
              {showResults && content && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="p-6 md:p-8 rounded-3xl bg-card border border-border/50 shadow-premium"
                >
                  <div className="prose prose-sm dark:prose-invert max-w-none [&_table]:w-full [&_table]:border-collapse [&_th]:bg-muted [&_th]:px-3 [&_th]:py-2 [&_th]:text-left [&_th]:text-xs [&_th]:font-semibold [&_td]:px-3 [&_td]:py-2 [&_td]:text-sm [&_td]:border-b [&_td]:border-border/50 [&_tr]:hover:bg-muted/50">
                    <ReactMarkdown>{content}</ReactMarkdown>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </section>
    </Layout>
  );
}
